### PR TITLE
Meetup API update

### PR DESCRIPTION
**Pull request by lukaszklis**
Switched the endpoint to make sure **ONLY** OTS's events are being considered.

### CODE REVIEW

**Comment by Kriesse** [comment]
lgtm, thanks for fixing this!

**Comment by jonicious** [comment]
Sorry for asking but what is the reason behind this? If I see this correctly, this way CSSclasses in other cities (e.g. Edinburgh or Hamburg) won't appear on the site, right?

**Comment by Kriesse** [comment]
@jonicious The reason was a bug where an unrelated meetup was listed that happened to have "CSSclasses" in its description.

Other events like Hamburg or Edinburgh should definitely be listed. @lukaszklis any ideas how to make that happen?

If using the meetup.com API won't solve this (which sooner or later will happen as other cities should be free to choose their own signup service), I propose to create manual posts for each event.

**Comment by lukaszklis** [comment]
@jonicious we've had a "bug" which showed an event of up.front since we used quite a generic search endpoint for the API. As a temporary fix we changed it to show only events shown from the OTS account, however since we're reviewing #24 we'll try to find out a better approach which is gonna work for other cities as well.

**Comment by jonicious** [comment]
@Kriesse @lukaszklis Alright, thanks for clearing this up and fixing the "bug"! :) If you have any question regarding #24, please feel free to reach out.

**Comment by Kriesse** [comment]
@jonicious Yup, thanks for all the work on #24, totally missed that! Will review on the weekend. Sorry for the long delay.

**Pull request merged**
