### PR TITLE
Rearrange "Learning Material" content

### PR DESCRIPTION
**Pull request by katrin-k**
The "Materials" page is currently hard to read with all of the content being on one page. This PR rearranges the Materials section so every article has its own page. 

- Adds an overview page on `/materials.html`, deletes “introduction” post since the intro is
now directly on materials page.
- Removes date from the post layout.
- Fixes post titles and in the posts, rearrange Table of Content sections.
- Check posts for “simply”, “just”, unneccessary exclamation marks,
dismissive phrases, etc.
- Reorders main navigation and level up “materials”, Reasoning: The site
is currently mainly used for the workshops and attendees should find
the page as quick as possible.

### CODE REVIEW

**Comment by jonicious** [comment]
Nice work! Thanks for doing this :) Do you have any idea why the build is failing and/or how to fix this?

**Comment by lukaszklis** [comment]
@jonicious `gem` requires a newer version of Ruby. Will open a PR to fix it

**Comment by lukaszklis** [comment]
@katrin-k I will open a separate PR where I upgrade all dependencies along with Travis improvements in a few minutes

**Comment by lukaszklis** [comment]
PR fixing the Travis config: #91.

**Comment by katrin-k** [comment]
Gracias you all!

**Comment by bastianalbers** [comment]
I'm a bit late to still approve, but also have to say: thanks a ton ❤️

**Pull request merged**
