### PR TITLE
Change jekyll destination folder to use new gh-pages-settings

### PR DESCRIPTION
**Pull request by schoenwaldnils**
https://github.com/blog/2228-simpler-github-pages-publishing

should also solve #36

### CODE REVIEW

**Comment by jonicious** [comment]
Thank you for your work, @schoenwaldnils! 👍 

>This lets you maintain documentation and code together on one branch, and open source maintainers can accept contributions for both in a single pull request.

Since the project has many build tasks, contributors won't be able to just update one file. They would have to update the original file and the built file which is inconvenient and most people won't know about it.

To me, built content does not belong to a repository which would be the case then. Although having the `gh-pages` branch is not ideal either, there is still some separation between the source files and built content.

I am more into the idea of @KlausTrainer he proposed in #36 to have a Grunt plugin that deploys the site automatically. One problem though is that the `master` branch does not always reflect the website because you would have to run the Grunt plugin first.

What do you think, @lukaszklis @verpixelt @Kriesse?

**Comment by lukaszklis** [comment]
Will look into this later today.

**Comment by schoenwaldnils** [comment]
How about using Travis to run the build task?
https://gist.github.com/domenic/ec8b0fc8ab45f39403dd
With my changes it could be simpler. Then there is no need for an extra branch.

**Comment by jonicious** [comment]
Hey @schoenwaldnils! Just set up Travis to let it run the deployment automatically after every master commit. Let's stay with the separate `gh-pages` branch (at least for now).

**Pull request closed without merging**
