### PR TITLE
Fix font loading issue

### PR DESCRIPTION
**Pull request by jonicious**

### CODE REVIEW

**Comment by jonicious** [comment]
Fixes #38

**Comment by jonicious** [comment]
Not sure about `data-ttf` and `data-woff2` since we don't use them anyway. Shouldn't we just delete them and go just with `data-woff`?

**Comment by lukaszklis** [comment]
@jonicious good point on the `ttf` font, this one we can remove. As for woff2 I'd keep it and adjust the font loading script later (at least then we won't forget about the double quotes). ;)

**Comment by lukaszklis** [comment]
Other than this, I tested it in a few browsers and it works perfectly (tu)

**Comment by verpixelt** [comment]
Yeah I'm with @lukaszklis on this. We should support woff2.

**Comment by jonicious** [comment]
At the moment, we are making an extra HTTP request to get font styles and store them in LocalStorage to prevent loading them another time when visiting another page. The `style.css` gets loaded every time. So the question is: Why do we want to store fonts in LocalStorage? Why not just have them in `style.css`, save another request and remove script that loads fonts? What do you think?

If that is okay for you, it would like to add styles for woff and woff2 to `style.scss` and remove the `ttf` font and script from the `head`.

**Comment by verpixelt** [comment]
The extra request happens only once. I'd rather not put 420KB (woff and woff2 combined) of encoded font-files into our main CSS file. Even Gzip this seems to be too much to me.

**Comment by fredericmarx** [comment]
Just some background information: Inlining webfonts used to be popular, but is now considered an anti-pattern, as the downsides mostly outweigh the benefits: [Web Font Anti-Patterns](https://www.bramstein.com/writing/web-font-anti-patterns.html) / [Web Font Anti-Patterns: Inlining](https://www.bramstein.com/writing/web-font-anti-patterns-inlining.html)

**Comment by verpixelt** [comment]
I appreciate you sharing this and I agree we should look at it again, but not now. This is consider to be a fix so we have a website for Sunday which looks like it is supposed to look.

**Comment by fredericmarx** [comment]
@verpixelt sorry for the confusion. I'm not suggesting to change anything, I was just providing some background information supporting your earlier statement:

> I'd rather not put 420KB (woff and woff2 combined) of encoded font-files into our main CSS file.

**Comment by verpixelt** [comment]
No need for an apology ;) You're right! I was confused :P

**Comment by verpixelt** [comment]
LGTM! @lukaszklis do you wanna have a look as well or shall I merge it?

**Pull request merged**
