### PR TITLE
Fix Travis deploy script

### PR DESCRIPTION
**Pull request by KlausTrainer**
Let's see if this is gonna work with the now correct remote address…

### CODE REVIEW

**Comment by KlausTrainer** [comment]
I thought that it would be a good idea to use the name and email of the last commit's author for the deploy commit as well. (Alternatively, we could use something like `Travis CI` and `travis-deploy@localhost`, I guess.)

Looks like now there's only some [GitHub-API-token-encypting-and-putting-it-into-Travis-config-Fu](http://ricostacruz.com/cheatsheets/travis-gh-pages.html) missing, which I happily leave to someone with write access to the repository ;) *nudge nudge* @jonicious

**Comment by KlausTrainer** [comment]
I know this is unintuitive, but `$TRAVIS_BRANCH` is the default branch when building pull requests.

Assuming the deployment is working soon, we probably want to enable "Build pushes" and disable "Build pull requests" in the Travis CI settings, so that we don't deploy every pull request, but only the stuff that has landed in the master branch ;)

If you'd like to solve this in a different way, or if you'd like to learn more details about the underlying issues, see https://graysonkoonce.com/getting-the-current-branch-name-during-a-pull-request-in-travis-ci/.

**Comment by jonicious** [comment]
>I thought that it would be a good idea to use the name and email of the last commit's author for the deploy commit as well.

Like that!

I just enabled "Build pushes" and disabled "Build pull requests" in the Travis CI settings.

**Comment by KlausTrainer** [comment]
Thanks! 🎉

**Pull request merged**
